name: Serverless Vue

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

  deploy-dev:
    needs:
      - build
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://sign.taurus.cd.dev.peanut996.cn

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Deploy to Tencent CloudBase
        uses: TencentCloudBase/cloudbase-action@v2.0.1
        env:
          STAGE: ${{secrets.STAGE}}
          APP_NAME: ${{ secrets.APP_NAME }}
        with:
          secretId: ${{ secrets.TENCENT_SECRET_ID }}
          secretKey: ${{ secrets.TENCENT_SECRET_KEY }}
          envId: ${{secrets.ENV_ID}}

  deploy-prod:
    runs-on: ubuntu-latest
    needs:
      - deploy-dev
    environment:
      name: prod
      url: https://sign.taurus.cd.prod.peanut996.cn

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Deploy to Tencent CloudBase
        uses: TencentCloudBase/cloudbase-action@v2.0.1
        env:
          STAGE: ${{secrets.STAGE}}
          APP_NAME: ${{ secrets.APP_NAME }}
        with:
          secretId: ${{ secrets.TENCENT_SECRET_ID }}
          secretKey: ${{ secrets.TENCENT_SECRET_KEY }}
          envId: ${{secrets.ENV_ID}}
